### ISSUE TITLE
Add explicit check box for "write" permission of API key in admin page

### ISSUE THREAD

**Issue by gimite** [google/personfinder#123]
Currently, filling the domain name for write access subsumes the "write" permission, but it's confusing. We should add an explicit check box for "write" permission.

**Comment by kspviswa** [comment]
@gimite 

I would like to work on this issue.

**Comment by gimite** [comment]
It would be great! To clarify, we should have both checkbox and the text field for the domain name. If the user checks the checkbox and leave the domain field empty, we should show an error.

**Comment by kspviswa** [comment]
@gimite 

Thanks for the clarification. I shall work on it and raise a pull request for you to review.
