### ISSUE TITLE
"Mark records as duplicate" table has too much space

### ISSUE THREAD

**Issue by gimite** [google/personfinder#128]
![e50zdfufg](https://cloud.githubusercontent.com/assets/15363/9402234/b56d8f68-4815-11e5-9d9e-fcda7a73d247.png)

To see this page, create two person records with a common family name, search for the family name, click "duplicat marking mode", check both of them, and click "Mark records as duplicate".

**Comment by kspviswa** [comment]
@gimite 

I couldn't view the screenshot. On clicking the link, I was asked enter my google credentials. On entering my gmail ID, it doesn't proceed further. Maybe the sreenshot reside in Google's private servers.

Let me know if I can work on this.

BR,
Viswa

**Comment by gimite** [comment]
Yeah sorry it was our internal page. I replaced it with an externally visible one.

**Comment by gimite** [comment]
It would be great if you work on it.

**Comment by kspviswa** [comment]
Hi, 

I had created a pull request containing the fix for this issue. It is here : https://github.com/google/personfinder/pull/160 .

Please review & accept the merge, if deemed fit.

**Comment by gimite** [comment]
As I mentioned in #160, it has actually been fixed by #146. Sorry for miscommunication.
