### ISSUE TITLE
Add photo upload API

### ISSUE THREAD

**Issue by gimite** [google/personfinder#13]
One of frequent requests by third party developers, including a developer of PF mobile app.

**Comment by kspviswa** [comment]
Hi,

Could you please elaborate on this issue. I do see a phtoto upload dialog in official google pf site. Since photo upload feature is already available, I'm trying to understand what you meant by photo upload API. I'm sorry if this is obvious question. I'm quite new to pf

**Comment by gimite** [comment]
Sorry for slow response.

It should be fine to reuse "write" API access to permit photo upload.

Your suggested flow should work too, but I prefer a flow like this:

- A user performs POST request to /REPO/api/upload_photo?key=API_KEY with a image data. (Directly putting image data to the HTTP request body would be good.)
- It returns simple XML just with a URL to the uploaded photo (with randomly generated ID) e.g., 
`<response><url>http://....jpg</url></response>`
- The user then hits normal "write" API with the URL to the photo.

I prefer this flow because the person/note record in Person Finder is basically immutable. We don't allow people to modify them after they are created. In your suggested flow, we ask people to modify a part of person record (i.e., the photo) after it is created.

@skywhale , any comment?

**Comment by skywhale** [comment]
I agree with you. When we built the photo uploading demo for the intern's
Android app, we basically did exactly what you described.

**Comment by kspviswa** [comment]
@gimite Thanks for your valuable comment. I have a follow-up question though. So the photo-upload API, would just save the uploaded photo with random-ID and return the generated random-ID as a response. Are we going to maintain a seperate dir to save the photo locally inside pf directory structure or do you prefer some cloud API to be used. [google-drive, onedrive etc].

**Comment by gimite** [comment]
You can do the same thing as existing logic to upload a photo while
creating a new record on the web UI. It stores the image in Photo model in
datastore.

You can call photo.create_photo in the similar way as in
create.Handler#post:
https://github.com/google/personfinder/blob/master/app/create.py#L96
The method does "generate random ID" and "save the image in the datastore".

2015年5月8日(金) 14:53 kspviswa <notifications@github.com>:

**Comment by kspviswa** [comment]
@gimite 

Is this issue still open? After pretty long gap I'm back to PF :) . So just want to know this, before resuming on this issue.

**Comment by kspviswa** [comment]
Hi,

I had created a pull request for this feature request here : https://github.com/google/personfinder/pull/109

Please review and merge the pull request if deemed fit.

BR,
VIswa

**Comment by kspviswa** [comment]
@gimite 

I had opened another fresh pull request https://github.com/google/personfinder/pull/129 after doing clean-ups & addressing your review comments.

Please review the new pull request https://github.com/google/personfinder/pull/129 and accept the merge if deemed fit. 

I'm hereby closing this pull request.

**Comment by gimite** [comment]
Thanks, I will take a look. Next time, it would be nicer to update the existing pull request instead of creating another one. You can just push your extra changes to the existing branch associated with the pull request.
