### ISSUE TITLE
Unable to register and search by kanji if "Require query words to have at least 2 characters" is selected

### ISSUE THREAD

**Issue by prazuma** [google/personfinder#135]
When "Require query words to have at least 2 characters" is selected, can't register record with given/family name with 2-letter kanji characters. It should be accepted since it says "at least 2 characters".

**Comment by gimite** [comment]
Clarified the bug description. Since it says "require at least 2 characters", it would be fine to reject one-letter given/family names. But still it should not reject 2-letter names.
