### ISSUE TITLE
Automatically call setup_datastore() on the first HTTP access to the newly created application instance

### ISSUE THREAD

**Issue by gimite** [google/personfinder#140]
Currently you need to manually call setup_datastore() for a newly created application instance, as instructed in https://github.com/google/personfinder/wiki/GettingStarted . It would be nice to automate it.

To implement it, we need to be careful about mutual exclusion. It's quite likely that multiple HTTP requests are made in parallel. We need some kind of mutual exclusion, or maybe just show a [initialize] button when not initialized, and let user manually click the button to initialize.

This is subitem of #78 .

**Comment by clobrano** [comment]
Hi, I would like to work on this issue

**Comment by gimite** [comment]
https://github.com/google/personfinder/pull/190
