### ISSUE TITLE
Update localized messages for vietnamese

### ISSUE THREAD

**Issue by ntduong** [google/personfinder#148]

**Comment by gimite** [comment]
Did you find any particular issue?

**Comment by ntduong** [comment]
I think some messages sound a bit weird to me. Also, some entries are missing vietnamese counterpart. Overall, it is a minor issue though.

**Comment by ntduong** [comment]
Perhaps just ignore it for now. I'm looking at other issues.

**Comment by gimite** [comment]
Replied via the corp email.
