### ISSUE TITLE
Update the message to let users know that they can search by person name + location

### ISSUE THREAD

**Issue by gimite** [google/personfinder#189]
Update "Enter the person's name, parts of the name, or mobile phone number."

After we launch full text search.

**Comment by Stephanie1125** [comment]
Is update message needed for new UI too?
![search](https://cloud.githubusercontent.com/assets/15961861/18864854/3a1aa980-84d3-11e6-965e-76f78b9e7173.png)

**Comment by gimite** [comment]
Let's leave it now and ask @nmakida to confirm. We may remove the message itself.

**Comment by Stephanie1125** [comment]
Okay! Let's discuss about it this Friday
