### ISSUE TITLE
Use cssselect() instead of range-based element lookup in the server tests

### ISSUE THREAD

**Issue by gimite** [google/personfinder#245]
Replace first(), firsttag(), alltags(), etc. with scrape.Document.cssselect() in server tests (under tests/server_test_cases). This allows more standard lookup using CSS selector + DOM operations.

Remove range-based methods in scrape.py once the replace is done.

**Comment by skywhale** [comment]
Let me finish the remainder

**Comment by gimite** [comment]
Ooh great, thanks. It would be great even if you only send pull request for what you have done so far.

**Comment by skywhale** [comment]
#268 sent.

**Comment by skywhale** [comment]
I mistakenly merged two tiny changes to the master. (one big one was reverted) Both should be safe, but could you please confirm?

**Comment by gimite** [comment]
LGTM for the two changes.

**Comment by skywhale** [comment]
The PR merged.
