### ISSUE TITLE
HTTPException: Deadline exceeded in jp_mobile_carriers.py

### ISSUE THREAD

**Issue by gimite** [google/personfinder#256]
This exception happens occasionally:

HTTPException: Deadline exceeded while waiting for HTTP response from URL: http://dengon.docomo.ne.jp/inoticelist.cgi

For URL like this: http://google.org/personfinder/japan/results?role=seek&query=090xxxxxxx

We should handle the exception.

**Comment by d268** [comment]
I'm looking into this bug. I think we can just add some try-catch around `urllib2.urlopen` inside the `look_up_number` function in `jp_mobile_carriers.py` ([here](https://github.com/google/personfinder/blob/master/app/jp_mobile_carriers.py#L150) and [here](https://github.com/google/personfinder/blob/master/app/jp_mobile_carriers.py#L157)).
My question is: Should we wrap the exception in our own customized exception and `raise`? Or should just we log about it and return? Current [comments](https://github.com/google/personfinder/blob/master/app/jp_mobile_carriers.py#L146) on the function say we should throw exception when failed to scrape, though. 
Shall we decide on how to handle the exception?

**Comment by gimite** [comment]
We can either just throw the exception as is (as we currently do) or raise a customized exception. In either case, result.py should catch the exception and show a nicer error message, saying that we encountered an error connecting to our backend.
