### ISSUE TITLE
TypeError: <lambda>() got an unexpected keyword argument 'namespace' (py.test version: 2.9.2)

### ISSUE THREAD

**Issue by Stephanie1125** [google/personfinder#271]
Update py.test version from 2.6.4 to 2.9.2 and appear the following error:
```
TypeError: <lambda>() got an unexpected keyword argument 'namespace'
```
This error is fixed by edited the code in tests/unit_tests.py:
Change the line 44 from
```
 lambda *args: original_parse_setoption(*args) or [os.environ['TESTS_DIR']]
```
to
```
lambda *args, **kwargs: original_parse_setoption(*args, **kwargs) or [os.environ['TESTS_DIR']]
```

**Comment by gimite** [comment]
Once you fix the issue, click "Close issue" button instead of putting "Fixed" in the comment. (I have just done for this one.)

Also, you should also refer from your pull request to the issue by putting "#" + issue number somewhere in your pull request description.
