### ISSUE TITLE
Nepal earthquake April 2015

### ISSUE THREAD

**Issue by isaacbaldwin** [google/personfinder#28]
Looking for Isaac Baldwin from Manchester he was trekking with a Sherpa and Max Downman around the annapurna ring when the quake hit this morning 07503337405

**Comment by gimite** [comment]
This is an issue tracker for Person Finder development, not a form to share person information. Please use Person Finder instead:
https://google.org/personfinder/2015-nepal-earthquake

In Person Finder, I found one person record with the same name, reported as safe:
https://google.org/personfinder/2015-nepal-earthquake/view?family_name=&given_name=&id=2015-nepal-earthquake.personfinder.google.org%2Fperson.4513284645453824&query=Isaac+Baldwin&role=seek

Is he the person you are looking for?

Our thoughts are with you.
