### ISSUE TITLE
Kanji Handling problems(Chinese and Japanese)

### ISSUE THREAD

**Issue by matthew-z** [google/personfinder#280]
Currently full_text_search will try to romanise kanji, but it has some problems.

A few Chinese kanji has a different pronunciation and romaji when it is a part of a family name. For example, "曾" could be romanised into "Ceng" in most cases, but it must be romanised into "Zeng" when it is used as a family name. This transformation is quite fixed, so a dictionary about it can tackle it easily. In additional, since Hong Kong and Taiwan people use a different sachem to romanise Chinese kanji from Mainland Chinese, the romanise method could be improved for them.

Furthermore, the romanise method cannot handle some rare Japanese family names in some cases. For example, 小鳥遊 should be TAKANASHI instead of  ODORIYU or KOTORIYU

**Comment by gimite** [comment]
Thanks for the feedback!

For Chinese, we currently rely on unidecode library. Do you know of any other library which supports the person name specific romanization, or a list of exceptions available somewhere? Or maybe can you make one?

We have special handling for Japanese, based on a dictionary here (big):
https://raw.githubusercontent.com/google/personfinder/master/app/japanese_name_location_dict.txt
We believe that it covers most of Japanese names. Unfortunately it missed 小鳥遊, so I'm adding it at #281. It's quite rare name, though...

**Comment by matthew-z** [comment]
No problem, I have added some supports for romanising Chinese family name at #282.
