### ISSUE TITLE
Add server test for SMS interface in Spanish, French and Haitian Creole

### ISSUE THREAD

**Issue by gimite** [google/personfinder#303]
Currently PersonNoteTests.test_sms_api only tests English queries:
https://github.com/google/personfinder/blob/master/tests/server_test_cases/person_note_tests.py#L2633

We should add test for Spanish, French and Haitian Creole queries there.

You can find query keywords for each language here:
https://github.com/google/personfinder/blob/master/app/api.py#L627

Some notes on the SMS interface:
Person Finder doesn't directly handle SMSes from users. They are handled by Google internal SMS gateway. When the gateway receives an SMS, it sends an XML HTTP request to Person Finder, and sends back its response to the user via SMS.

**Comment by AwesomeTurtle** [comment]
Hi ! 
Can you provide more details about this issue ?

**Comment by gimite** [comment]
Updated the description. Let us know if you have any further questions.

BTW I will go to vacation from now until Feb 28. @kevinalle in our team will reply any questions and review pull requests during my vacation. But he may ask you to wait for my answers/reviews in some cases. Sorry for inconvenience.
