### ISSUE TITLE
Should add Name or mobile phone on the top of search box when disable full_text_search

### ISSUE THREAD

**Issue by Stephanie1125** [google/personfinder#311]
+ Disable full text search
![disable full text search](https://cloud.githubusercontent.com/assets/15961861/19587834/62b64efe-979c-11e6-8c7d-172d5b34d7ab.png)

+ Enable full text search
![fulltextsearch](https://cloud.githubusercontent.com/assets/15961861/19587840/6ec20abc-979c-11e6-8fad-fa2cb44f4186.png)

Should keep the name or mobile phone number when full text search is disable because we removed the message for new ui (see #189)

**Comment by sup4boyz** [comment]
Harold Junior White JR.
(213)300-4038

**Comment by sup4boyz** [comment]
LOS  Angeles, CA , 90069
 8491 West Sunset Blvd.
 West Hollywood, CA. 90069
