### ISSUE TITLE
Make our code work with the latest unidecode library

### ISSUE THREAD

**Issue by gimite** [google/personfinder#329]
It looks our code doesn't work if we update unidecode library to the latest version (per @AwesomeTurtle ).

We should make it work with the latest unidecode, and move it from app/unidecode to app/vendors (by adding it to requirements.txt).

**Comment by martialp** [comment]
I tried to update the unidecode library to the lastest version, and I didn't notice any problems. I think it is safe to update.

**Comment by AwesomeTurtle** [comment]
Agree with @martialp , I just ran 

```
# rm -r app/unidecode 
# pip install -t app/vendors unidecode
# tools/all_tests
```

And there is no problem. So we could remove `unidecode` from `app/` and install it with pip into `app/vendors/`
Sorry !

**Comment by gimite** [comment]
Thanks for the confirmation. I send a pull request to update it for review.
