### ISSUE TITLE
Add Travis Integration ? 

### ISSUE THREAD

**Issue by AwesomeTurtle** [google/personfinder#340]
I made this continuous integration using Travis. I wondering if we can add it to the main project or if it is useless ? 

https://github.com/AwesomeTurtle/personfinder/tree/awesometurtle-travis-integration

**Comment by gimite** [comment]
Oh that looks nice. How can we add one?

**Comment by AwesomeTurtle** [comment]
I don't know how it works from your account. 
For my part, I have to click on my account icon, then `integrations`. Choose Travis CI. Configure it by adding `personfinder` repo. 
Travis will trigger when a `.travis.yml` will be in the next commit.

You can find another method [there](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo#integrate-your-github-project-with-travis-ci)

**Comment by gimite** [comment]
So we first need to put .travis.yml into our repository, right? Maybe can you send a pull request to add that?

**Comment by AwesomeTurtle** [comment]
I could send a pull request. But I made some major modifications: I added a docker-compose, and modified Dockerfile. It is easier to work with Docker on a Travis Integration. 
I can send a pull request, and we will check if modifications are too majors.

**Comment by gimite** [comment]
Sounds good, thanks!

Just curious, what is benefit using docker-compose in this case, with just a single docker container?

**Comment by AwesomeTurtle** [comment]
A docker-compose is better than using a bash script for launching container (setting shared volumes, ports,etc)  and it is more scalable and maintainable. Moreover, the app could be scalable in the future ( if we want to add more services, I don't know..)

**Comment by gimite** [comment]
Thanks for explanation! Then using docker-compose sounds good.

**Comment by gimite** [comment]
Configured one and looks working. Great, thanks!
https://travis-ci.org/google/personfinder

**Comment by AwesomeTurtle** [comment]
Yes, well done ! 
We could clean up useless files related to Docker, but later.
