### ISSUE TITLE
Move the language selector to the top

### ISSUE THREAD

**Issue by gimite** [google/personfinder#344]
We should probably move the language selector to the top:

![nmqvnhaifei](https://cloud.githubusercontent.com/assets/15363/23500037/df745a20-ff71-11e6-996d-8fa57b1bc698.png)

It should be inside the top gray header if possible. If it's hard, it may be also acceptable to put it below the gray and white headers.

Reason: For users who open Person Finder in foreign language, it should be easy for them to notice that they can change the language.

**Comment by RajibHossen** [comment]
I will work on this issue.

**Comment by gimite** [comment]
Great, thanks for your contribution!

**Comment by RajibHossen** [comment]
Made a pull request changing codes according to your comments.

**Comment by gimite** [comment]
As I mentioned in #356, I found an issue with #350's UI on mobile, decided to move it below the header bar, and made a change in #356. Sorry for back and forth.
