### ISSUE TITLE
The top bar's hight is too big in the global home page

### ISSUE THREAD

**Issue by gimite** [google/personfinder#351]
The gray top bar's hight is too big in the global home page:
https://google.org/personfinder/
![cuukuse0mcy](https://cloud.githubusercontent.com/assets/15363/24692864/ec355c1e-1a15-11e7-89c7-a6d72fa2a084.png)

I believe it should be in the same hight as in other pages like:
https://google.org/personfinder/japan
![vwzodgjzxof](https://cloud.githubusercontent.com/assets/15363/24692878/0064a0dc-1a16-11e7-9526-223335366de3.png)

**Comment by gimite** [comment]
Looks like it is caused by .header rule in sidebar.css. I believe the entire .header rule is unnecessary, maybe an unexpected leftover from the old UI. It also causes a needless horizontal scroll bar.

**Comment by RajibHossen** [comment]
I will work on this issue.
