### ISSUE TITLE
[discussion] Cloud Platform

### ISSUE THREAD

**Issue by AwesomeTurtle** [google/personfinder#359]
Hi ! 

It is not really an issue, but I am just wondering : what is the workflow of this application ? 

Could we enable a Continuous Deployment ? Each time a PR is merged into master, Travis could build a new Docker image of `Person Finder` and deploy it with Kubernetes or whatever to Google Cloud Platform on a `dev` server. Like so, each time a new release is ready, production server will pull latest Docker image of Person Finder.

Just a discussion :smiley:

**Comment by gimite** [comment]
Thanks for the suggestion!

We are currently deploying it manually. Automating it is an atractive idea, but I believer we want to control when to push.

* We often do cacual manual testing on production deploys. Unfortunately our automated tests are not perfect...
* We deploy with special care while Person Finder is actively used for any disaster. We really don't want to break our production during the period.

**Comment by AwesomeTurtle** [comment]
Ok, I understand ! Thanks for your answering. I am closing this discussion.
