### ISSUE TITLE
Continuous Integration failed

### ISSUE THREAD

**Issue by AwesomeTurtle** [google/personfinder#362]
Since last build (2 months ago), CI does not success.

6 tests have failed especially into  `person_note_tests.py` file. 

Code has not changed since 2 latest months, so I suppose we have a requirement who is not fixed. And this requirements has been upgraded beetween may and today.

**Comment by AwesomeTurtle** [comment]
(I am on it btw 😄 )

**Comment by gimite** [comment]
Great, thanks!

**Comment by AwesomeTurtle** [comment]
If you have any ideas, I reverted my fork to this commit [4c0acf6](https://github.com/google/personfinder/commit/04c0acf628b2ada903884e2b3f72bad33d398056) and tests failed always at the same place. 
Also, I fixed Python requirements with "good" version from 3 months ago. And It does not work.
