### ISSUE TITLE
AMP page contains script tags

### ISSUE THREAD

**Issue by githaruo** [google/personfinder#390]
Hi team,

I found some script tags in the [AMP start page](https://www.google.org/personfinder/japan/amp_start?#development=1). See console on your chrome browser.

**Comment by gimite** [comment]
Oh I see. I wonder why it's not caught by:
https://search.google.com/test/amp?id=TK4IrNMOAgVCDyq-WHULIA

The two scripts are for Analytics and Google Tag Manager. Looks like they both provide a way to support AMP. Can you take a look? @myoshimu may know some hints.

**Comment by githaruo** [comment]
I chatted with @myoshimu about this part. I'll add amp-analytics tags to gtm.html.template.

**Comment by gimite** [comment]
Thanks for taking a look!
