### ISSUE TITLE
tools/all_tests depends on old version of pytest

### ISSUE THREAD

**Issue by nworden** [google/personfinder#416]
tools/all_tests uses _pytest.config.Parser, but Parser appears to have moved to the argparsing module in version 3.6.2.
I'll try to find a way to avoid depending directly on Parser; since they moved it without a mention in the release notes, I'm not sure they meant for it to be used like that. Otherwise I'll just update the reference to it to use its new module.

**Comment by nicoddemus** [comment]
> I'll try to find a way to avoid depending directly on Parser; since they moved it without a mention in the release notes, I'm not sure they meant for it to be used like that. 

Although not part of the public API, it definitely should be at least mentioned in the CHANGELOG, sorry about that. 👍

**Comment by nworden** [comment]
No apology needed!

**Comment by gimite** [comment]
Actually it might be safer to reimplement the parser in our code base than depending on a private API, though it's redundant. We are probably interested in a small subset of the flags anyway (I personally have only used `-k`).
