### ISSUE TITLE
Upgrade django and lxml in the dependency

### ISSUE THREAD

**Issue by gimite** [google/personfinder#447]
As warned by tools/gae:

    WARNING appinfo.py:1651 django version "1.9" is deprecated, use one of: "1.4", "1.11" 
    WARNING appinfo.py:1651 lxml version "2.3" is deprecated, use one of: "3.7.3"

**Comment by nworden** [comment]
Forgot to reference the issue from the PR, but lxml was upgraded to 3.7.3 in PR #512.

**Comment by nworden** [comment]
Upgraded Django to 1.11 in PR #613.
