### ISSUE TITLE
tools/babel contains Python 3 syntax errors

### ISSUE THREAD

**Issue by cclauss** [google/personfinder#460]
* tools/babel/messages/extract.py
* tools/babel/messages/frontend.py

These two files contain legacy __print__ statements that would fail as syntax errors on Python 3.  The [current babel](https://pypi.org/project/Babel) supports Python 3 so it should either be pip installed or re-vendored.  Discovered but not fixed https://github.com/google/personfinder/pull/459/commits/f99351aa4af59bfc5d97cfe55c1f6334c686d016#r238889957

**Comment by gimite** [comment]
Thanks for finding it. Actually there is also app/vendors/babel which I believe is newer. We should probably refer to it instead.

**Comment by cclauss** [comment]
Why not just __pip install babel__ instead of vendoring it in?

**Comment by gimite** [comment]
App Engine upload tool only uploads files in `app` directory. So all dependency libraries, including babel, must be located inside `app` before running the app. There would still be an option not to track `app/vendors` with Git, and instead let individual developers install them, though.

**Comment by gimite** [comment]
Filed #463 for migration to app/vendors/babel.

**Comment by gimite** [comment]
Let me close this one. I believe we should just fix #463 instead of fixing tools/babel.
