### ISSUE TITLE
Remove tools/babel and use app/vendors/babel instead

### ISSUE THREAD

**Issue by gimite** [google/personfinder#463]
tools/babel is old and is also a subset of babel.

See #460 for context.

**Comment by cclauss** [comment]
Actually we are also pip installing Babel in __requirements.txt__.  Best practice would be to remove the vendoring if possible.

**Comment by gimite** [comment]
requirements.txt is a file used to generate app/vendors. See:
https://github.com/google/personfinder/blob/master/app/vendors/README.md

**Comment by nworden** [comment]
Fixed in #651.
