### ISSUE TITLE
Upgrade google-api-python-client

### ISSUE THREAD

**Issue by nworden** [google/personfinder#497]
The version we're using now (1.7.4) doesn't specify that it supports Python 3.7 (the version that App Engine's Python 3 runtime uses). The latest version (1.7.7) supports both 2.7 and 3.7, so we should upgrade to it, just to be safe, before we switch to the Python 3 App Engine runtime.

**Comment by ParthS007** [comment]
Hi @nworden
I want to work on this Issue. How should I proceed with this?
Thanks

**Comment by nworden** [comment]
Hi Parth!
This is a good starter issue because most of the work would just be setting up what you need for PF development (instructions [here](https://github.com/google/personfinder/wiki/GettingStarted)). Once you do that, yeah, you would update requirements.txt, install the new version to app/vendors (instructions about that [here](https://github.com/google/personfinder/blob/56622624bc65e7e9c5f9aa7342067d0e7d0013c0/app/vendors/README.md)), and then run the tests to make sure everything still works.

**Comment by ParthS007** [comment]
Hi @nworden, I just found that `google-api-python-client` had a new release yesterday i.e 1.7.8. 
Should I upgrade it to `1.7.8` or keep it `1.7.7`?
The latest version supports both 2.7 and 3.7. 
Waiting for your reply.

**Comment by nworden** [comment]
That's great, thanks for noticing! Yeah, let's go with the new one, 1.7.8.

**Comment by ParthS007** [comment]
Okay, Making PR shortly.
