### ISSUE TITLE
Upgrade simplejson

### ISSUE THREAD

**Issue by nworden** [google/personfinder#499]
The version we're using (3.10.0) doesn't specifically support Python 3.7. The latest version doesn't either, and it doesn't seem to be all that actively developed, but they are testing with Python 3.7, so we should probably be ok if we upgrade to the latest version.

**Comment by ParthS007** [comment]
Hi @nworden 
I want to work on this Issue. How should I proceed with this?
Thanks

**Comment by ParthS007** [comment]
@nworden Should I go ahead with this Issue?

**Comment by nworden** [comment]
Sure! I suggest making sure you work off the latest version of the master branch (i.e., including PR #518, which I just merged in) to avoid merge conflicts.

**Comment by ParthS007** [comment]
Yes, I will make PR only after pulling the latest changes.
