### ISSUE TITLE
Set up Python 3 testing

### ISSUE THREAD

**Issue by nworden** [google/personfinder#508]
Most of our tests will fail right now if we try to run them with Python 3, so we'll need to set up something that runs a specific subset of tests; we can add to that set as we make more code Python 3-compatible.

**Comment by ParthS007** [comment]
@nworden I am familiar with writing tests. Please let me know if I can help you with this Issue.

**Comment by nworden** [comment]
This issue actually isn't about writing the tests themselves, but just having our existing tests run under both versions of Python. It's not very high-priority, because right now hardly any of our tests would pass under Python 3 anyway :(
If you're interested in testing itself, you might prefer an issue like #168 or #490. We also have a couple older issues related to test flakes (like #226).

**Comment by ParthS007** [comment]
okay, I will have a look at the linked issue.
Do you have any workflow already designed for migration from `Python 2.7` to  `Python 3`?

**Comment by nworden** [comment]
We've only just started doing Python 3 work, and we don't expect to actually do the migration anytime soon because App Engine's Python 3 runtime is still in beta. Apart from the library upgrades, I'm starting by running python-modernize over files when I have time to kill, to get them compatible with both Python 2 and 3. TBH, doing that stuff might be particularly difficult for someone who's new to Person Finder, because the parts that python-modernize can't do automatically are parts that might require a good degree of familiarity with Person Finder. I expect I'll have to refer to gimite (who's been working on PF for many years) for help making sure I don't break anything myself, especially around unicode name handling.

**Comment by nworden** [comment]
Turns out I was doing it wrong -- Docker installs Python itself so it doesn't really matter what version of Python Travis is set up with. Inconveniently, Ubuntu doesn't seem to have Python 3.7 (or even 3.6) in its repositories, and I'd rather not depend on other repos (or build Python from source every time we run tests). I'll see if we can run our tests outside Docker, and otherwise I guess we can use Python 3.5 for the time being.

**Comment by nworden** [comment]
I take it back: the latest version of Ubuntu has Python 3.7 available, but my Docker base image was an older version of Ubuntu.

**Comment by nworden** [comment]
Really done now, in PR #582.
