### ISSUE TITLE
add .editorconfig file

### ISSUE THREAD

**Issue by mohitkyadav** [google/personfinder#529]
Defing style guide rules in a **.editorconfig** file, DOS/Windows style line endings cause errors in running the project, **editorconfig** file tells editors to use linux style line endings in all files by default.

**Comment by nworden** [comment]
As far as I know this is the first time this has come up. @gimite has this come up before that you know of?
If this is specific to a particular editor or a small number of editors: IMO configuration of this sort shouldn't be checked in. Feel free to add .editorconfig to .gitignore though.

**Comment by gimite** [comment]
No, AFAIK this is the first time.

According to https://editorconfig.org/, it (at least aims to) be a general config file across different editors. And looks like Github supports it by default (though I don't know what that mean). So IMHO it sounds like a good idea to have one submitted.

**Comment by ParthS007** [comment]
I want to send the patch for it.
Should I go ahead?

**Comment by nworden** [comment]
Yeah if it's widely used that seems fine. Sorry for my ignorance.
