### ISSUE TITLE
Virtual Keyboard is deprecated

### ISSUE THREAD

**Issue by nworden** [google/personfinder#534]
We still have [some code](https://github.com/google/personfinder/blob/56622624bc65e7e9c5f9aa7342067d0e7d0013c0/app/resources/static/vk.js#L15) kicking around for Google's Virtual Keyboard, which [is deprecated](https://developers.google.com/virtual-keyboard/v1/getting_started). It looks like the deprecation was announced in 2011, with a support period of 3 years. I might be trying to use it wrong, but it doesn't look like it works at all anymore.

I imagine we can expect that people's phones/browsers are set up to handle their language of choice these days, so hopefully there's no longer a need for this and we can just get rid of it, but I'll wait for confirmation from someone who routinely types in a language other than English.

BTW, in case anyone gets confused like I did: there's another (apparently totally different) Google product that's [also called Virtual Keyboard](https://www.google.com/inputtools/services/features/virtual-keyboard.html), but it's a Chrome extension/Android app. The Virtual Keyboard we're using is JS that we serve as part of our frontend.

**Comment by nworden** [comment]
It just occurred to me that an advantage of something like the JS virtual keyboard is that it'd be useful in situations with shared computers (e.g., at a camp/shelter) where people who speak a variety of languages would use the same browser. Since the old VK is deprecated, I'm not sure there's a good path for us to address that problem on our side, but we could encourage govt. agencies or NGOs to use the new Chrome extension virtual keyboard (which could be useful for other things too, not just PF).

**Comment by gimite** [comment]
This isn't an issue in Japan since you can type Japanese in all computers/phones sold in Japan. But I don't know the situation in other languages. I believe it was more for countries like India, so it may be good if we can get input from people in such countries.

**Comment by nworden** [comment]
It turns out the reason this wasn't working for me is that it's only enabled for Urdu. Remarkably, it does still work, at least as far as I can tell as a non-Urdu speaker.
It'd be useful to get some insight on whether there was a specific reason this was set up for Urdu (Hiroshi, if you don't know I'll try Pete). Frankly I'm still inclined to get rid of it unless there's a really good reason to keep it though, because I think keeping it around is fairly risky. Eventually it's bound to break or get deleted, and once that happens we're unlikely to know it's broken until we need to launch for an event in Pakistan (i.e., we'll only find out "the hard way").

**Comment by nworden** [comment]
Removed in PR #567. Further discussion on the decision to drop it is in the PR description.
