### ISSUE TITLE
Add subscription API

### ISSUE THREAD

**Issue by gimite** [google/personfinder#6]
Add an API to subscribe to a record with an email address.

Probably as an API separated from existing write API?

Request by a developer of PF mobile app.

**Comment by drewm11235** [comment]
Hi - I'm interested in contributing to this open source project and I'm looking for some clarification.

I'm trying to learn how to build an API and I think I'm successfully figuring it out.

However, I'm looking for further guidance with the exact assignment. The existing write API, is that api.py? What variable name stores email address in the code? Where is email address stored as record?

If this isn't the write place to post this question, apologies, and please let me know where to post.

**Comment by gimite** [comment]
Thanks for the interest in contributing to this project!

I'm sorry, but I have just found that there's actually already a subscription API (api/subscribe).

If you are interested, it would be great if you pick up another issue from:
https://github.com/google/personfinder/issues

**Comment by drewm1123** [comment]
Hi Hiroshi,

Ok, thanks!

I'm definitely interested. I'm trying to get into the open source space as
an intro to my first software engineer job. Long-term I want to become a
software engineer and also contribute to this project on a continuing basis.

Do have any suggestions for what issue to work on?

Drew

**Comment by gimite** [comment]
#19 or #52 may be a good start. We will import issues from the old site in the end of this week, so I expect more issues registered soon.
