### ISSUE TITLE
Consider .gitignoring app/vendors

### ISSUE THREAD

**Issue by nworden** [google/personfinder#617]
`requirements.txt` should be all we really need to check in, and changes including stuff under app/vendors are a hassle to review (e.g., PR #616).

Under the Python 3 runtime, App Engine will install our dependencies from `requirements.txt` itself ([docs](https://cloud.google.com/appengine/docs/standard/python3/runtime#dependencies)), so we won't even need to upload the files to AE ourselves, and IMO we should certainly drop them from version control at that point. The question is whether we should drop them from version control now, while we're still on the Python 2 runtime and need to upload these files to AE.

**Comment by gimite** [comment]
I believe we originally decided to check in app/vendors to make local development and releases easier. But I agree that it's annoying, and I'm OK to remove it from version control if:
* It is clearly documented how to locate them, if it still needs to be located manually for dev app server.
* We make sure that we don't accidentally make a release without locating app/vendors. Maybe it is already ensured by running unit/server tests in our release script?

**Comment by nworden** [comment]
Maybe we should add thr `pip inatall` command to our release script, in case someone upgrades a library in `requirements.txt` but the new version doesn't affect our tests.

**Comment by gimite** [comment]
That's a good point and sounds like a good idea.

**Comment by nworden** [comment]
This is done and the docs have been updated.
