### ISSUE TITLE
Add a delete button for uploaded files

### ISSUE THREAD

**Issue by gimite** [google/personfinder#65]
Need to add a “delete button” in the upload photo section. If the user uploads a wrong file (wrong extension) by accident but he does not have any file to upload he cannot save any information in the form until he inputs some picture.

Copied from https://docs.google.com/document/d/1M_kGYkEdlN4Ii7DHwyLgqHan3vusfohNWjxVJ_Ggt_o/edit?hl=en_US&pli=1

Users can delete the file by clicking "Upload" again and click "Cancel". But it may be hard to notice.

**Comment by kspviswa** [comment]
Yes. I too felt the same. Infact I was looking for this button when I was first experimenting PF. Accidentally I again clicked the Upload button, only then I realized about this behaviour.

Just to add a little bit here. Even if you click on the "uploaded file name", you can have a chance of uploading another file.

Further more, the uploaded file name is not proper. It is truncated that, even the file is not properly visible. It would be good, if the truncation be done, only if the file name goes beyond the column boundry.

In the below example, the uploaded file name is `motivation.jpg`. However you can see the file name is truncated even for such a small name.
![image](https://cloud.githubusercontent.com/assets/7476271/9703205/87623192-5499-11e5-914c-5964247e85ec.png)

**Comment by kspviswa** [comment]
And... Can I work on this issue???

**Comment by Stephanie1125** [comment]
This is added in the new UI
![photo_upload](https://cloud.githubusercontent.com/assets/15961861/18864115/c27832f6-84cf-11e6-9ee0-769d62280431.png)
