### ISSUE TITLE
PR checks not always running

### ISSUE THREAD

**Issue by nworden** [google/personfinder#710]
I've noticed recently that tests aren't getting run automatically for new pull requests. Today there was also an issue with the CLA check (it didn't get re-run as expected on PR #709, but I've confirmed on our side that pollyMath did sign it). I don't know of any recent changes we've made that might have caused this, but GH's and Travis CI's status pages both look good, so it's probably us.

**Comment by kshithijiyer** [comment]
We can close this issue right? I see that the patch is already merged.

**Comment by kshithijiyer** [comment]
> We can close this issue right? I see that the patch is already merged.

@nworden ?

**Comment by nworden** [comment]
Thanks Kshithij, yeah we can close this.
