### ISSUE TITLE
tar xvfz does not work to extract PIL 1.1.7 in GettingStarted

### ISSUE THREAD

**Issue by ryosuketc** [google/personfinder#758]
`tar xvfz` in [GettingStarted](https://github.com/google/personfinder/wiki/GettingStarted) does not work for PIL 1.1.7 in the [Download](http://effbot.org/downloads/Imaging-1.1.7.tar.gz) link there.

```shell
% tar xvfz Imaging-1.1.7.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The reason seems to be because it is not a gzipped file - instead it is a POSIX tar archive file.
```shell
 % file Imaging-1.1.7.tar.gz 
Imaging-1.1.7.tar.gz: POSIX tar archive (GNU)
```

Hence `z` option needs to be removed.
```shell
 % tar xvf Imaging-1.1.7.tar.gz 
```

**Comment by gimite** [comment]
Hm this looks like a bug of effbot.org because the file name says .tar.gz but the file is not gzipped. But we should update the instruction anyway. Thanks for the report!

**Comment by ryosuketc** [comment]
@gimite Done.
https://github.com/google/personfinder/wiki/GettingStarted/_compare/f3d3b099acfbdc8c319412c7413d27c85b4e1d6a...c672db51b905c113cedcc8aaef7fb83c97dd3226
