### ISSUE TITLE
Automate Environment setup

### ISSUE THREAD

**Issue by gimite** [google/personfinder#78]
The Getting Started Guide explains how to install all tools required to develop PersonFinder as well as their version.
However, sometimes it can be painful to make sure this is working fine and that we have the right setup.

It would be great to be able to have something more automatic: either some sort of image of a setup to clone (and project owner would update this image regularly when the tools versions are upgraded) or some script to run which will install what is missing with the correct version...

**Comment by clobrano** [comment]
What about a Docker container? I just started looking around in this project, so I am not 100% sure that this solution will suit it

**Comment by clobrano** [comment]
Well, I had time to made some tests and I managed to complete the steps from the "Getting Started" page within a docker image with this configuration:

* all the tools and dependencies in the docker container
* the personfinder's source code in a host's folder shared with the container
* the gae test server running inside the container, but accessible from the host's web browser

**Comment by gimite** [comment]
Thanks for the suggestion and pull request! I will take a look.

There is another separated issue that you need to call setup_datastore() manually when you create a new app instance, as instructed in https://github.com/google/personfinder/wiki/GettingStarted . It should be done automatically on the first visit.

**Comment by clobrano** [comment]
I thought it was only a way to get some example data to start working on something.
I will have a look on how to do it automatically on container's creation.

**Comment by gimite** [comment]
Yeah but anyway you need some repositories to test anything, and I believe setup_datastore() also performs some global initialization. It's required also when you create a new real AppEngine instance (not local one) for testing. So I prefer a solution in AppEngine code, not limited to a local instance in Docker container.

**Comment by clobrano** [comment]
I'm not sure I have understood. Is it that you would prefer that running the web server the first time will call somehow setup_datastore programmatically?

I found out that there is the possibility to run both the Person Finder's server AND another script that calls setup_datastore the first time the Docker container is run. There still a problem tough, since the Person Finder's server is not run in localhost (otherwise it won't be visible in host's browser) and then the access to db would require a password (root is fine) I am not able to pass it automatically, yet.

**Comment by gimite** [comment]
> I'm not sure I have understood. Is it that you would prefer that running the web server the first time will call somehow setup_datastore programmatically?

Yes.

> I found out that there is the possibility to run both the Person Finder's server AND another script that calls setup_datastore the first time the Docker container is run. 

I prefer to implement the auto setup inside our AppEngine code, not as part of Docker initialization. The reason is that we also sometimes run our test server in AppEngine, not localhost:
https://github.com/google/personfinder/wiki/GettingStarted#step-6-optional-run-the-app-on-appengine
If we implement it inside AppEngine code, then it will also work on test servers in AppEngine too.

**Comment by clobrano** [comment]
> I prefer to implement the auto setup inside our AppEngine code, not as part of Docker initialization.

I agree.

So, If you are ok with that, I would not change this pull request. This way when the Docker container starts, the developer can either run the development server or  do other stuff on the environment if he/she needs. 

For the setup_datastore issue, I can add a (temporary) notes about how to run this command with Docker. Moreover, if an issue about the setup_datastore inside your AppEngine code is already open I would be glad to work on it.

**Comment by gimite** [comment]
> For the setup_datastore issue, I can add a (temporary) notes about how to run this command with Docker. Moreover, if an issue about the setup_datastore inside your AppEngine code is already open I would be glad to work on it.

Yeah the issue is open. I filed a separated issue #140 . It would be great if you work on it. Please show your interest there if you will work on it.

**Comment by gimite** [comment]
> So, If you are ok with that, I would not change this pull request. This way when the Docker container starts, the developer can either run the development server or do other stuff on the environment if he/she needs.

Sounds good to me.

**Comment by clobrano** [comment]
I saw that API server and Admin server run on localhost even if I am providing a --host parameter to tools/gae app run. I will look for a fix for this

**Comment by clobrano** [comment]
I've fixed the issue with Admin and API server. From my side this can be merged
