### ISSUE TITLE
"Home country" not requested when creating a Record but then it is displayed as blank

### ISSUE THREAD

**Issue by gimite** [google/personfinder#79]
How to reproduce on test.googlepersonfinder.appspot.com

1) Create a Record.

2) In the "home address" forms, it collects street name, neighborhood, city, province/state but it does not ask for a country.

3) Then when you view this created record, it displays "Home country:	"

**Comment by kspviswa** [comment]
@gimite 

I would like to work on this bug.

**Comment by kspviswa** [comment]
@gimite 

I had created a pull request https://github.com/google/personfinder/pull/113 to merge the commit that contains fix for this bug. Please review and accept merge, if deemed fit.

PS : I don't understand why my commits are aggregating into single pull request.

**Comment by gimite** [comment]
> PS : I don't understand why my commits are aggregating into single pull request.

You should make a branch from the master branch, instead of branching from kspviswa:kspviswa-photo_upload_API_new. i.e., kspviswa:kspviswa-bugfix_#79 should not contain the photo upload API change. In this case, I will cherry-pick only the relevant commit, so you can just leave it.
