### ISSUE TITLE
Integrate with Google Search

### ISSUE THREAD

**Issue by gimite** [google/personfinder#81]
From a customer feedback.

Due to our deletion policy and to avoid crawling, we cannot simply allow Google to index PF record pages. But it might be possible to add Person Finder onebox in Google Search.

1.A google search for data entered in person finder does not appear in a google search of Firstname;Lastname or other forms.
2.Adding data from Person-finder to Google index would greatly expand it's useability and create hits for others searching for lost family.

**Comment by kspviswa** [comment]
@gimite 

This would be a real value add for PF

**Comment by nworden** [comment]
I'm going to close this issue. I don't think we could freely discuss this on an external forum so it's probably better to file it internally.
