### ISSUE TITLE
Two photo upload fields in create form are a bit confusing

### ISSUE THREAD

**Issue by skywhale** [google/personfinder#87]
Both Person and Note records accept photos now, which means that on the initial "I have information about someone" page, there is a Photo upload area in both the left and the right column.  This is confusing when a user is first entering information about someone, so we should only show the Photo area for the Person record and hide the Photo area for the Note record on this initial entry page.

**Comment by skywhale** [comment]
Let's revisit as part of UI revamp.

**Comment by kspviswa** [comment]
@skywhale @gimite 

I would like to work on this feature request. Can I ?

**Comment by gimite** [comment]
We are working on refreshing the UI, and we are planning to fix this as a part of the refresh. So can you avoid working on it for now?

**Comment by kspviswa** [comment]
@gimite 

Sure.

**Comment by Stephanie1125** [comment]
Should we do this in the new UI too (hide the Photo section in Status card in the create page)?
But I think it might not be very confusing in the new UI cause we separate two photo section with cards (one in "Identifying information" card and the other in "status" card) and also we have notes("If you have a photo of this person, upload it or enter its URL address." and "To attach a photo to this note, upload it or enter its URL.") for two sections.

**Comment by gimite** [comment]
Hmm I feel it's still confusing, but you can confirm with @nmakida .

**Comment by Stephanie1125** [comment]
okay, i think we can discuss about this on Friday's meeting
