### ISSUE TITLE
Allow only valid email address with @ in email subscription

### ISSUE THREAD

**Issue by gimite** [google/personfinder#9]
I saw a case where email field contains a string without "@" and a cron job was failing due to it. Check if we verify email address correctly.

**Comment by kspviswa** [comment]
I would like to work on this bug. I started off with cloning pf, but then stalled on where to start. While I'm comfortable with normal python, I'm new to django & google app engine. Can you please provide me some pointers to  how to start? Is there any bootstrap & configure script to start / set-up?

**Comment by gimite** [comment]
Hello @kspviswa ,

It's great to hear that you are interested in development of Person Finder. Here is a GettingStarted doc:
https://github.com/google/personfinder/wiki/GettingStarted

Let me know if anything is unclear.

**Comment by Aloknayan** [comment]
@kspviswa  I would also like to contribute, The situations same on this end comfortable with python, I was hoping maybe we can work togather.

**Comment by kspviswa** [comment]
@Aloknayan Welcome to pf. To get started please look @ gettingstarted link as suggessted by @gimite . BTW I've started working on this issue. I would suggest you to work on some other issue, to prevent our efforts being duplicated.

@gimite Is there any way, to assign the issues to ourselves ? Something liking picking ?

**Comment by gimite** [comment]
@kspviswa You can just write your interest here as you have already done.

**Comment by skywhale** [comment]
Thank you very much kspviswa@ for the great contribution. The change is going to be merged to the default branch and pushed at the next server deployment (hopefully very soon).

**Comment by kspviswa** [comment]
@skywhale Thanks for your helpful reviews and motivation. @gimite Thanks for pointing to quick start link, which enabled be to *start quickly* . 

BTW could you help me in selecting next bug? I'm eager to contribute more :)

**Comment by kspviswa** [comment]
@skywhale  @gimite Can this bug be closed?

**Comment by gimite** [comment]
Actually the original bug says that I once found a record with an invalid mail address in the data store in the server. Since you pointed out that there was already a validation in the server side, it shouldn't have happened. I will close this bug after verifying that there is no other data flow to put the address without validation.

**Comment by nworden** [comment]
It's possible to enter an invalid email address for the found person (email_of_found_person). I couldn't find any code that tries to send emails to that address, so I'm not sure it could have caused a cron job to fail, but it's been 2.5 years, so maybe there used to be code that needed it to be valid.

**Comment by nworden** [comment]
It seems like a deliberate decision was made to only validate email addresses when they're used for subscriptions (the email validation code is within the subscription class). I'll check with Pete or Nobu to see if there's any product reason not to validate non-subscription emails.

**Comment by gimite** [comment]
> I'm not sure it could have caused a cron job to fail, but it's been 2.5 years

As far as I know, we only used subscription email to send emails.

**Comment by nworden** [comment]
I think I figured this out: when records are deleted, messages are sent to associated emails (`app/delete.py`, line 74). Those emails are validated client-side, but not server-side.
