### ISSUE TITLE
Support full text search beyond names

### ISSUE THREAD

**Issue by skywhale** [google/personfinder#93]
This should be relative simple to implement with the new Search API provided by GAE.
https://developers.google.com/appengine/docs/python/search/

Please note that we probably need to make sure a search query matches at least a part of person name; otherwise, the feature could allow querying for a neighborhood name and scrape a list of people there, which we agreed is a capability we don't want to provide with ordinary users to protect users' privacy.

**Comment by gimite** [comment]
Mark as dup of #67
