### ISSUE TITLE
Simplify "I'm this person" flow

### ISSUE THREAD

**Issue by skywhale** [google/personfinder#96]
Can we simplify the flow for creating a person record for _myself_? (How popular is this use case?)

In particular, auto-fill the following fields:
  Author's name: Person's name
  Status: I'm this person
  Have you personally talked with this person: YES

**Comment by skywhale** [comment]
Let's revisit as part of UI revamp.

**Comment by Stephanie1125** [comment]
I believe this is fixed in the new UI
![info](https://cloud.githubusercontent.com/assets/15961861/18830644/8899735a-841c-11e6-88c8-19060034dd46.png)

**Comment by gimite** [comment]
Yes. Can you put the pull request ID which fixed this issue here and mark this as closed?
